Interservice communication configuration
cherrytwist/Client.Web pull request #24
Opened 2020-09-15 05:49 UTC by Bogoev91

### Describe the background of your pull request

Extract data source endpoint address into an environment variable

What does your pull request do? Does it solve a bug (which one?), add a feature?

Makes the GraphQL endpoint datasource configurable - it was hardcoded until now

To be discussed - as of now, the docker build won't pass unless there is a running server instance from which the graphql schema is retrieved - graphql client code is regenerated each time a built is run.

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/cherrytwist/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/cherrytwist/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/cherrytwist/Coordination/blob/master/LICENSE 
     and the contributor license agreement: tba

2020-09-15 05:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/cherrytwist/Client.Web?pullRequest=24) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/cherrytwist/Client.Web?pullRequest=24) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/cherrytwist/Client.Web?pullRequest=24) it.</sub>

2020-09-15 07:35 UTC, atstojanov requested changes

2020-09-16 05:40 UTC, Bogoev91 commented on Dockerfile
> +RUN echo "REACT_APP_GRAPHQL_ENDPOINT="${GRAPHQL_ENDPOINT_ARG} > /app/.env
Not quite sure on how to pass environment variables to codegen task though - if we are using a custom url for the server, the schema needs to be regenerated each time right? I've mentioned this in my pr comment. This has a huge downside - it needs a running server to get  its schema from. Shall we just regenerate the schema by hand and remove this step from dockerfile alltogether?

2020-09-16 06:47 UTC, Bogoev91 commented on Dockerfile
> +RUN echo "REACT_APP_GRAPHQL_ENDPOINT="${GRAPHQL_ENDPOINT_ARG} > /app/.env
Discussed within the team - automatic client regeneration isn't needed. Removed from dockerfile.

2020-09-16 07:17 UTC, atstojanov approved these changes

2020-09-16 07:17 UTC, merged