Tagset/Reference components
cherrytwist/Client.Web pull request #449
Opened 2021-01-21 13:43 UTC by atstojanov

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/cherrytwist/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/cherrytwist/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/cherrytwist/Coordination/blob/master/LICENSE 
     and the contributor license agreement: tba

2021-01-22 08:42 UTC, valentinyanakiev requested changes

2021-01-22 08:42 UTC, valentinyanakiev commented on src/components/Admin/Common/InputField.tsx
> +        disabled={readOnly}
disabled should be removed

2021-01-22 08:42 UTC, valentinyanakiev commented on src/models/Profile.ts
> +export type Reference = {
Move all profile entities to Profile.ts and use them from here (at the moment this type is not referenced anywhere and overlaps with the one in User.ts)

2021-01-22 10:16 UTC, atstojanov commented on src/components/Admin/Common/InputField.tsx
> +        disabled={readOnly}
Not removed, but controlled separately.

2021-01-22 10:25 UTC, valentinyanakiev commented
![Screenshot_2021-01-22_12-24-12](https://user-images.githubusercontent.com/7090348/105479227-e4577800-5cac-11eb-8031-4206140fbd98.png)
The offset between reference fields is bigger than the rest of the form on the admin user edit page.

2021-01-22 10:26 UTC, valentinyanakiev requested changes
Code looks OK, just have a look at the offset between references.

2021-01-25 10:38 UTC, valentinyanakiev approved these changes

2021-01-25 10:38 UTC, merged