Client 337
cherrytwist/Client.Web pull request #484
Opened 2021-03-02 16:44 UTC by atstojanov

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated
- [ ] I've read the contributing document https://github.com/cherrytwist/.github/blob/master/CONTRIBUTING.md
- [ ] I've read and understand the Code of Conduct https://github.com/cherrytwist/.github/blob/master/CODE_OF_CONDUCT.md
- [ ] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/cherrytwist/Coordination/blob/master/LICENSE 
     and the contributor license agreement: tba

2021-03-02 16:47 UTC, atstojanov commented on src/components/LoginPage.tsx
> +      '/auth/login',
Must be read from configuration

2021-03-10 11:55 UTC, valentinyanakiev requested changes
Overall looks good, just fix the typo and create the proxy endpoints from the config. The rest looks OK to me.

2021-03-10 11:55 UTC, valentinyanakiev commented on src/models/Constantes.ts
> +export const TOKEN_KEY = 'accessToken';
Constants.ts not Constantes.ts - there is a typo

2021-03-10 11:55 UTC, valentinyanakiev commented on src/setupProxy.js
> +    createProxyMiddleware({
This configuration should be dynamic. If the endpoint of Simple Auth Provider is changed in the config - this is not reflected here, and I have a working example:
1. Docker compose the server project - it was changed to map 3003:3002 so Demo and Server project don't collide
2. Try to login with simple auth

It doesn't work and no error message is show, simply nothing happens when 'login' is clicked.

2021-03-10 15:18 UTC, valentinyanakiev approved these changes

2021-03-10 15:29 UTC, merged